name: typescript-app-build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        shell: bash
        run: npm install
      - name: Build
        shell: bash
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: production-build
          path: build/

  cypress1:
    runs-on: ubuntu-latest
    needs: [ "build" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
      - uses: actions/download-artifact@v3
        with:
          name: production-build
          path: build/
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.2 # use the explicit version number
        with:
          build: npm run build
          start: npm start

  cypress2:
    runs-on: ubuntu-latest
    needs: [ "build" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
      - uses: actions/download-artifact@v3
        with:
          name: production-build
          path: build/
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.2 # use the explicit version number
        with:
          build: ls build/
          start: sudo npx serve --ssl-cert ops/cert.pem --ssl-key ops/key.pem -p 443 --no-port-switching  --single build
        env:
          CYPRESS_baseUrl: https://localhost
