name: typescript-app-build

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - run: echo build
      - run: sleep 30
  e2e:
    needs: [build]
    uses: ./.github/workflows/cypress.yaml
    secrets: inherit
    with:
      local: true
