name: merge dependabot updates
on:
  pull_request_target:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{secrets.GITHUB_TOKEN}}
#      - name: Dependabot metadata
#        id: metadata
#        uses: dependabot/fetch-metadata@v1.3.5
#        with:
#          github-token: "${{ secrets.GITHUB_TOKEN }}"
#      - run: "echo update-type: ${{ steps.metadata.outputs.update-type }}"
#      - name: Enable auto-merge for Dependabot PRs
#        #if: ${{steps.metadata.outputs.update-type == 'version-update:minor'}}
#        run: gh pr merge --auto --squash "$PR_URL"
#        env:
#          PR_URL: ${{github.event.pull_request.html_url}}
#          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
