name: deploy
on:
  workflow_call:
    inputs:
      foo:
        description: 'Serve the production build from a local server'
        required: true
        type: string
        default: 'local'
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - run: echo local=${{ github.event.inputs.foo }}
      - run: echo hej
        if: ${{ github.event.inputs.foo == 'local' }}
