name: deploy
on:
  workflow_call:
    inputs:
      local:
        description: 'Serve the production build from a local server'
        required: false
        type: boolean
        default: true
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - run: echo local=${{ github.event.inputs.local }}
      - run: echo hej
        if: ${{ github.event.inputs.local == 'true' }}
