name: deploy
on:
  workflow_call:
    inputs:
      foo:
        description: 'Serve the production build from a local server'
        required: true
        type: boolean
        default: true
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - run: echo local=${{ inputs.foo }}
      - run: echo hej
        if: ${{ inputs.foo }}
