on:
  pull_request:
  push:
    branches:
      - main
jobs:
  push-to-repo-hello-service:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo A
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to Repo B
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        gh pr list --repo erikmartino/flux-clusters
        git remote add repo-b https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/erikmartino/hello-service.git
        git fetch repo-b
        git checkout -b push-me repo-b/main
        date >date.txt
        git add date.txt
        git commit -m "date"
        git push repo-b HEAD:push-me
